import { useMemo, useState } from "react";
import { Search, Clock } from "lucide-react";

const DATA = {
  "Smileys & People": [
    ["😀", "grinning happy"],
    ["😃", "smile happy"],
    ["😄", "grin happy"],
    ["😁", "beaming"],
    ["😆", "laughing"],
    ["😅", "sweat smile"],
    ["🤣", "rofl laughing"],
    ["😂", "joy tears"],
    ["🙂", "slight smile"],
    ["🙃", "upside down"],
    ["😉", "wink"],
    ["😊", "blush"],
    ["😇", "innocent angel"],
    ["🥰", "love hearts"],
    ["😍", "heart eyes love"],
    ["🤩", "star struck"],
    ["😘", "kiss"],
    ["😗", "kissing"],
    ["😚", "kiss closed"],
    ["😙", "kiss smile"],
    ["😋", "yum tasty"],
    ["😛", "tongue"],
    ["😜", "wink tongue"],
    ["🤪", "zany crazy"],
    ["😝", "squint tongue"],
    ["🤑", "money mouth"],
    ["🤗", "hug"],
    ["🤭", "hand over mouth"],
    ["🤫", "shush quiet"],
    ["🤔", "thinking"],
    ["🤐", "zipper mouth"],
    ["🤨", "raised eyebrow"],
    ["😐", "neutral"],
    ["😑", "expressionless"],
    ["😶", "no mouth"],
    ["😏", "smirk"],
    ["😒", "unamused"],
    ["🙄", "roll eyes"],
    ["😬", "grimace"],
    ["🤥", "lying"],
    ["😌", "relieved"],
    ["😔", "pensive sad"],
    ["😪", "sleepy"],
    ["🤤", "drool"],
    ["😴", "sleeping"],
    ["😷", "mask sick"],
    ["🤒", "thermometer"],
    ["🤕", "bandage hurt"],
    ["🤢", "nauseated"],
    ["🤮", "vomit"],
    ["🤧", "sneeze"],
    ["🥵", "hot"],
    ["🥶", "cold"],
    ["🥴", "woozy drunk"],
    ["😵", "dizzy"],
    ["🤯", "mind blown"],
    ["🤠", "cowboy"],
    ["🥳", "party"],
    ["😎", "cool sunglasses"],
    ["🤓", "nerd"],
    ["🧐", "monocle"],
    ["😕", "confused"],
    ["😟", "worried"],
    ["🙁", "frown"],
    ["☹️", "frowning"],
    ["😮", "open mouth"],
    ["😯", "hushed"],
    ["😲", "astonished"],
    ["😳", "flushed"],
    ["🥺", "pleading"],
    ["😦", "frowning open"],
    ["😧", "anguished"],
    ["😨", "fearful"],
    ["😰", "anxious sweat"],
    ["😥", "sad relieved"],
    ["😢", "cry"],
    ["😭", "sob cry"],
    ["😱", "scream fear"],
    ["😖", "confounded"],
    ["😣", "persevere"],
    ["😞", "disappointed"],
    ["😓", "downcast sweat"],
    ["😩", "weary"],
    ["😫", "tired"],
    ["🥱", "yawn"],
    ["😤", "triumph"],
    ["😡", "rage angry"],
    ["😠", "angry"],
    ["🤬", "cursing"],
    ["😈", "devil"],
    ["👿", "devil angry"],
    ["💀", "skull"],
    ["💩", "poop"],
    ["🤡", "clown"],
    ["👹", "ogre"],
    ["👺", "goblin"],
    ["👻", "ghost"],
    ["👽", "alien"],
    ["🤖", "robot"],
    ["😺", "cat smile"],
    ["❤️", "red heart love"],
    ["🧡", "orange heart"],
    ["💛", "yellow heart"],
    ["💚", "green heart"],
    ["💙", "blue heart"],
    ["💜", "purple heart"],
    ["🖤", "black heart"],
    ["🤍", "white heart"],
    ["💔", "broken heart"],
    ["💕", "two hearts"],
    ["💞", "revolving hearts"],
    ["💓", "beating heart"],
    ["💗", "growing heart"],
    ["💖", "sparkling heart"],
    ["💘", "cupid"],
    ["💝", "heart gift"],
    ["👍", "thumbs up like"],
    ["👎", "thumbs down"],
    ["👌", "ok"],
    ["✌️", "peace"],
    ["🤞", "fingers crossed"],
    ["🤟", "love you"],
    ["🤘", "rock on"],
    ["🤙", "call me"],
    ["👈", "point left"],
    ["👉", "point right"],
    ["👆", "point up"],
    ["👇", "point down"],
    ["☝️", "index up"],
    ["✋", "raised hand"],
    ["🤚", "back hand"],
    ["🖐️", "hand fingers"],
    ["🖖", "vulcan"],
    ["👋", "wave hello"],
    ["🤝", "handshake"],
    ["🙏", "pray thanks"],
    ["👏", "clap"],
    ["🙌", "raise hands"],
    ["👐", "open hands"],
    ["🤲", "palms up"],
    ["💪", "muscle strong"],
    ["🦾", "mech arm"],
    ["🦿", "mech leg"],
    ["🦵", "leg"],
    ["🦶", "foot"],
    ["👂", "ear"],
    ["👃", "nose"],
    ["🧠", "brain"],
    ["👀", "eyes"],
    ["👁️", "eye"],
    ["👅", "tongue"],
    ["👄", "lips"],
  ],
  "Animals & Nature": [
    ["🐶", "dog"],
    ["🐱", "cat"],
    ["🐭", "mouse"],
    ["🐹", "hamster"],
    ["🐰", "rabbit"],
    ["🦊", "fox"],
    ["🐻", "bear"],
    ["🐼", "panda"],
    ["🐨", "koala"],
    ["🐯", "tiger"],
    ["🦁", "lion"],
    ["🐮", "cow"],
    ["🐷", "pig"],
    ["🐸", "frog"],
    ["🐵", "monkey"],
    ["🐔", "chicken"],
    ["🐧", "penguin"],
    ["🐦", "bird"],
    ["🐤", "chick"],
    ["🦆", "duck"],
    ["🦅", "eagle"],
    ["🦉", "owl"],
    ["🦇", "bat"],
    ["🐺", "wolf"],
    ["🐗", "boar"],
    ["🐴", "horse"],
    ["🦄", "unicorn"],
    ["🐝", "bee"],
    ["🐛", "bug"],
    ["🦋", "butterfly"],
    ["🐌", "snail"],
    ["🐞", "ladybug"],
    ["🐜", "ant"],
    ["🦗", "cricket"],
    ["🕷️", "spider"],
    ["🐢", "turtle"],
    ["🐍", "snake"],
    ["🦎", "lizard"],
    ["🐙", "octopus"],
    ["🦑", "squid"],
    ["🦐", "shrimp"],
    ["🦞", "lobster"],
    ["🦀", "crab"],
    ["🐡", "blowfish"],
    ["🐠", "fish"],
    ["🐟", "fish"],
    ["🐬", "dolphin"],
    ["🐳", "whale"],
    ["🐋", "whale"],
    ["🦈", "shark"],
    ["🌸", "cherry blossom"],
    ["🌹", "rose"],
    ["🌺", "hibiscus"],
    ["🌻", "sunflower"],
    ["🌷", "tulip"],
    ["🌱", "seedling"],
    ["🌲", "tree"],
    ["🌳", "tree"],
    ["🌴", "palm"],
    ["🌵", "cactus"],
    ["🌿", "herb"],
    ["☘️", "shamrock"],
    ["🍀", "clover"],
    ["🍁", "maple"],
    ["🍂", "leaf"],
    ["🍃", "leaves"],
    ["🌾", "wheat"],
    ["🌊", "wave"],
    ["🔥", "fire"],
    ["⭐", "star"],
    ["🌟", "star glow"],
    ["✨", "sparkles"],
    ["⚡", "lightning"],
    ["☀️", "sun"],
    ["🌤️", "sun cloud"],
    ["⛅", "cloud sun"],
    ["☁️", "cloud"],
    ["🌧️", "rain"],
    ["⛈️", "storm"],
    ["🌩️", "lightning cloud"],
    ["❄️", "snow"],
    ["⛄", "snowman"],
    ["🌈", "rainbow"],
    ["🌙", "moon"],
    ["🌛", "moon face"],
    ["🌕", "full moon"],
    ["🌍", "earth"],
    ["🪐", "planet"],
    ["🌌", "galaxy"],
  ],
  "Food & Drink": [
    ["🍎", "apple"],
    ["🍐", "pear"],
    ["🍊", "orange"],
    ["🍋", "lemon"],
    ["🍌", "banana"],
    ["🍉", "watermelon"],
    ["🍇", "grapes"],
    ["🍓", "strawberry"],
    ["🍈", "melon"],
    ["🍒", "cherry"],
    ["🍑", "peach"],
    ["🥭", "mango"],
    ["🍍", "pineapple"],
    ["🥥", "coconut"],
    ["🥝", "kiwi"],
    ["🍅", "tomato"],
    ["🍆", "eggplant"],
    ["🥑", "avocado"],
    ["🥦", "broccoli"],
    ["🥕", "carrot"],
    ["🌽", "corn"],
    ["🌶️", "chili"],
    ["🥒", "cucumber"],
    ["🥬", "lettuce"],
    ["🧄", "garlic"],
    ["🧅", "onion"],
    ["🥔", "potato"],
    ["🍠", "sweet potato"],
    ["🥐", "croissant"],
    ["🥖", "bread"],
    ["🍞", "bread"],
    ["🥨", "pretzel"],
    ["🥯", "bagel"],
    ["🧀", "cheese"],
    ["🥚", "egg"],
    ["🍳", "cooking"],
    ["🧇", "waffle"],
    ["🥞", "pancake"],
    ["🥓", "bacon"],
    ["🍔", "burger"],
    ["🍟", "fries"],
    ["🍕", "pizza"],
    ["🌭", "hot dog"],
    ["🥪", "sandwich"],
    ["🌮", "taco"],
    ["🌯", "burrito"],
    ["🥙", "pita"],
    ["🧆", "falafel"],
    ["🥘", "pan"],
    ["🍝", "pasta"],
    ["🍜", "ramen"],
    ["🍲", "stew"],
    ["🍛", "curry"],
    ["🍣", "sushi"],
    ["🍱", "bento"],
    ["🥟", "dumpling"],
    ["🍤", "shrimp"],
    ["🍙", "rice ball"],
    ["🍚", "rice"],
    ["🍘", "rice cracker"],
    ["🍥", "fish cake"],
    ["🥠", "fortune cookie"],
    ["🥮", "mooncake"],
    ["🍢", "oden"],
    ["🍡", "dango"],
    ["🍧", "ice"],
    ["🍨", "ice cream"],
    ["🍦", "soft ice"],
    ["🥧", "pie"],
    ["🧁", "cupcake"],
    ["🍰", "cake"],
    ["🎂", "birthday cake"],
    ["🍮", "custard"],
    ["🍭", "lollipop"],
    ["🍬", "candy"],
    ["🍫", "chocolate"],
    ["🍿", "popcorn"],
    ["🍩", "donut"],
    ["🍪", "cookie"],
    ["🌰", "chestnut"],
    ["🥜", "peanut"],
    ["🍯", "honey"],
    ["🥛", "milk"],
    ["☕", "coffee"],
    ["🍵", "tea"],
    ["🧃", "juice"],
    ["🥤", "cup straw"],
    ["🍶", "sake"],
    ["🍺", "beer"],
    ["🍻", "beers"],
    ["🥂", "clink"],
    ["🍷", "wine"],
    ["🥃", "whisky"],
    ["🍸", "cocktail"],
    ["🍹", "tropical"],
    ["🧉", "mate"],
    ["🍾", "champagne"],
  ],
  Activities: [
    ["⚽", "soccer"],
    ["🏀", "basketball"],
    ["🏈", "football"],
    ["⚾", "baseball"],
    ["🥎", "softball"],
    ["🎾", "tennis"],
    ["🏐", "volleyball"],
    ["🏉", "rugby"],
    ["🥏", "frisbee"],
    ["🎱", "billiards"],
    ["🏓", "ping pong"],
    ["🏸", "badminton"],
    ["🥊", "boxing"],
    ["🥋", "martial arts"],
    ["🥅", "goal"],
    ["⛳", "golf"],
    ["🏹", "archery"],
    ["🎣", "fishing"],
    ["🤿", "diving"],
    ["🥌", "curling"],
    ["🎿", "ski"],
    ["🛷", "sled"],
    ["🥌", "curling"],
    ["🎯", "target"],
    ["🎮", "game"],
    ["🕹️", "joystick"],
    ["🎲", "dice"],
    ["🧩", "puzzle"],
    ["♟️", "chess"],
    ["🎭", "theater"],
    ["🎨", "art"],
    ["🎬", "movie"],
    ["🎤", "mic"],
    ["🎧", "headphones"],
    ["🎼", "music"],
    ["🎵", "note"],
    ["🎶", "notes"],
    ["🎹", "piano"],
    ["🥁", "drum"],
    ["🎷", "sax"],
    ["🎺", "trumpet"],
    ["🎸", "guitar"],
    ["🎻", "violin"],
    ["🎤", "mic"],
    ["🎙️", "studio mic"],
    ["🏆", "trophy"],
    ["🥇", "gold"],
    ["🥈", "silver"],
    ["🥉", "bronze"],
    ["🏅", "medal"],
    ["🎖️", "military"],
    ["🎗️", "ribbon"],
    ["🎫", "ticket"],
    ["🎟️", "tickets"],
    ["🎪", "circus"],
    ["🚗", "car"],
    ["🚕", "taxi"],
    ["🚙", "suv"],
    ["🚌", "bus"],
    ["🚎", "trolley"],
    ["🏎️", "race car"],
    ["🚓", "police"],
    ["🚑", "ambulance"],
    ["🚒", "fire truck"],
    ["🚐", "van"],
    ["🚚", "truck"],
    ["🚛", "semi"],
    ["🚜", "tractor"],
    ["🛵", "scooter"],
    ["🏍️", "motorcycle"],
    ["🚲", "bike"],
    ["🛴", "kick scooter"],
    ["🚂", "steam train"],
    ["🚄", "train"],
    ["✈️", "airplane"],
    ["🛩️", "small plane"],
    ["🚀", "rocket"],
    ["🛸", "ufo"],
    ["🚁", "helicopter"],
    ["⛵", "sailboat"],
    ["🚤", "speedboat"],
    ["🛥️", "motor boat"],
    ["🚢", "ship"],
    ["⚓", "anchor"],
    ["🚉", "station"],
    ["🏝️", "island"],
    ["🏖️", "beach"],
    ["🏔️", "mountain"],
    ["🌋", "volcano"],
    ["🗻", "fuji"],
    ["🏕️", "camping"],
    ["🏠", "home"],
    ["🏢", "office"],
    ["🏥", "hospital"],
    ["🏦", "bank"],
    ["🏨", "hotel"],
    ["🏫", "school"],
    ["⛪", "church"],
    ["🕌", "mosque"],
    ["🕍", "synagogue"],
    ["🗼", "tokyo tower"],
    ["🗽", "statue"],
    ["🗿", "moai"],
    ["🎡", "ferris"],
    ["🎢", "roller coaster"],
  ],
  Objects: [
    ["⌚", "watch"],
    ["📱", "phone"],
    ["💻", "laptop"],
    ["⌨️", "keyboard"],
    ["🖥️", "desktop"],
    ["🖨️", "printer"],
    ["🖱️", "mouse"],
    ["💽", "minidisc"],
    ["💾", "floppy"],
    ["💿", "cd"],
    ["📀", "dvd"],
    ["📷", "camera"],
    ["📸", "camera flash"],
    ["📹", "video camera"],
    ["🎥", "movie camera"],
    ["📺", "tv"],
    ["📻", "radio"],
    ["🎙️", "mic"],
    ["⏰", "alarm"],
    ["⌛", "hourglass"],
    ["📡", "satellite"],
    ["🔋", "battery"],
    ["🔌", "plug"],
    ["💡", "bulb"],
    ["🔦", "flashlight"],
    ["🕯️", "candle"],
    ["🔥", "fire"],
    ["💸", "money fly"],
    ["💵", "dollar"],
    ["💰", "bag money"],
    ["💳", "credit card"],
    ["💎", "gem"],
    ["⚖️", "scale"],
    ["🔧", "wrench"],
    ["🔨", "hammer"],
    ["⚒️", "hammer pick"],
    ["🛠️", "tools"],
    ["⛏️", "pick"],
    ["🔩", "bolt"],
    ["⚙️", "gear"],
    ["🧱", "brick"],
    ["⛓️", "chains"],
    ["🧲", "magnet"],
    ["🔫", "gun"],
    ["💣", "bomb"],
    ["🧨", "firework"],
    ["🪓", "axe"],
    ["🔪", "knife"],
    ["🗡️", "dagger"],
    ["⚔️", "swords"],
    ["🛡️", "shield"],
    ["🚬", "cigarette"],
    ["⚰️", "coffin"],
    ["🪦", "headstone"],
    ["🏺", "amphora"],
    ["🔮", "crystal ball"],
    ["📿", "beads"],
    ["🧿", "nazar"],
    ["💈", "barber"],
    ["⚗️", "alembic"],
    ["🔭", "telescope"],
    ["🔬", "microscope"],
    ["🕳️", "hole"],
    ["🩹", "bandage"],
    ["🩺", "stethoscope"],
    ["💊", "pill"],
    ["💉", "syringe"],
    ["🩸", "drop blood"],
    ["🧬", "dna"],
    ["🦠", "microbe"],
    ["🧫", "petri"],
    ["🧪", "test tube"],
    ["🌡️", "thermometer"],
    ["🧹", "broom"],
    ["🧺", "basket"],
    ["🧻", "paper roll"],
    ["🚽", "toilet"],
    ["🚿", "shower"],
    ["🛁", "bath"],
    ["🧼", "soap"],
    ["🪥", "toothbrush"],
    ["🪒", "razor"],
    ["🧽", "sponge"],
    ["🧴", "lotion"],
    ["🛎️", "bellhop"],
    ["🔑", "key"],
    ["🗝️", "old key"],
    ["🚪", "door"],
    ["🪑", "chair"],
    ["🛋️", "couch"],
    ["🛏️", "bed"],
    ["🖼️", "frame"],
    ["🛍️", "shopping bag"],
    ["🎁", "gift"],
    ["🎈", "balloon"],
    ["🎏", "carp streamer"],
    ["🎀", "ribbon"],
    ["🎊", "confetti"],
    ["🎉", "party popper"],
    ["🎎", "dolls"],
    ["🏮", "lantern"],
    ["🎐", "wind chime"],
    ["🧧", "red envelope"],
    ["✉️", "envelope"],
    ["📩", "email"],
    ["📨", "incoming"],
    ["📧", "e-mail"],
    ["💌", "love letter"],
    ["📥", "inbox"],
    ["📤", "outbox"],
    ["📦", "package"],
    ["🏷️", "label"],
    ["📪", "mailbox"],
    ["📫", "mailbox"],
    ["📬", "mailbox"],
    ["📭", "mailbox"],
    ["📮", "postbox"],
    ["📯", "postal horn"],
    ["📜", "scroll"],
    ["📃", "page"],
    ["📄", "page facing"],
    ["📑", "bookmark tabs"],
    ["📊", "chart"],
    ["📈", "chart up"],
    ["📉", "chart down"],
    ["🗒️", "notepad"],
    ["🗓️", "calendar"],
    ["📆", "calendar"],
    ["📅", "calendar"],
    ["📇", "card index"],
    ["🗃️", "card file"],
    ["🗳️", "ballot"],
    ["🗄️", "file cabinet"],
    ["📋", "clipboard"],
    ["📁", "folder"],
    ["📂", "open folder"],
    ["🗂️", "dividers"],
    ["🗞️", "newspaper"],
    ["📰", "newspaper"],
    ["📓", "notebook"],
    ["📔", "notebook"],
    ["📒", "ledger"],
    ["📕", "red book"],
    ["📗", "green book"],
    ["📘", "blue book"],
    ["📙", "orange book"],
    ["📚", "books"],
    ["📖", "open book"],
    ["🔖", "bookmark"],
    ["🧷", "safety pin"],
    ["🔗", "link"],
    ["📎", "paperclip"],
    ["🖇️", "paperclips"],
    ["📐", "triangle ruler"],
    ["📏", "ruler"],
    ["🧮", "abacus"],
    ["📌", "pushpin"],
    ["📍", "round pin"],
    ["✂️", "scissors"],
    ["🖊️", "pen"],
    ["🖋️", "fountain pen"],
    ["✒️", "black nib"],
    ["🖌️", "brush"],
    ["🖍️", "crayon"],
    ["📝", "memo"],
    ["✏️", "pencil"],
    ["🔍", "magnify left"],
    ["🔎", "magnify right"],
    ["🔏", "lock pen"],
    ["🔐", "lock key"],
    ["🔒", "locked"],
    ["🔓", "unlocked"],
  ],
  Symbols: [
    ["❤️", "heart red"],
    ["🧡", "heart orange"],
    ["💛", "heart yellow"],
    ["💚", "heart green"],
    ["💙", "heart blue"],
    ["💜", "heart purple"],
    ["🖤", "heart black"],
    ["🤍", "heart white"],
    ["🤎", "heart brown"],
    ["💔", "heart break"],
    ["❣️", "heart exclaim"],
    ["💕", "two hearts"],
    ["💞", "hearts rotating"],
    ["💓", "heartbeat"],
    ["💗", "heart grow"],
    ["💖", "heart sparkle"],
    ["💘", "heart arrow"],
    ["💝", "heart gift"],
    ["💟", "heart deco"],
    ["☮️", "peace"],
    ["✝️", "cross"],
    ["☪️", "crescent"],
    ["🕉️", "om"],
    ["☸️", "dharma"],
    ["✡️", "star david"],
    ["🔯", "six point"],
    ["🕎", "menorah"],
    ["☯️", "yin yang"],
    ["☦️", "orthodox"],
    ["🛐", "worship"],
    ["⛎", "ophiuchus"],
    ["♈", "aries"],
    ["♉", "taurus"],
    ["♊", "gemini"],
    ["♋", "cancer"],
    ["♌", "leo"],
    ["♍", "virgo"],
    ["♎", "libra"],
    ["♏", "scorpio"],
    ["♐", "sagittarius"],
    ["♑", "capricorn"],
    ["♒", "aquarius"],
    ["♓", "pisces"],
    ["🆔", "id"],
    ["⚛️", "atom"],
    ["🉑", "accept"],
    ["☢️", "radioactive"],
    ["☣️", "biohazard"],
    ["📴", "phone off"],
    ["📳", "vibrate"],
    ["📵", "no phones"],
    ["🔞", "no under 18"],
    ["🔕", "no bell"],
    ["🔔", "bell"],
    ["🔊", "speaker loud"],
    ["🔉", "speaker mid"],
    ["🔈", "speaker low"],
    ["🔇", "speaker mute"],
    ["✅", "check"],
    ["❌", "cross"],
    ["❎", "cross box"],
    ["✔️", "check mark"],
    ["☑️", "checkbox"],
    ["🔘", "button"],
    ["🔴", "red circle"],
    ["🟠", "orange circle"],
    ["🟡", "yellow circle"],
    ["🟢", "green circle"],
    ["🔵", "blue circle"],
    ["🟣", "purple circle"],
    ["⚫", "black circle"],
    ["⚪", "white circle"],
    ["🟤", "brown circle"],
    ["🔺", "red triangle"],
    ["🔻", "red tri down"],
    ["🔸", "small orange"],
    ["🔹", "small blue"],
    ["🔶", "large orange"],
    ["🔷", "large blue"],
    ["🔳", "square white"],
    ["🔲", "square black"],
    ["⬛", "black square"],
    ["⬜", "white square"],
    ["🟥", "red square"],
    ["🟧", "orange square"],
    ["🟨", "yellow square"],
    ["🟩", "green square"],
    ["🟦", "blue square"],
    ["🟪", "purple square"],
    ["🟫", "brown square"],
    ["⭐", "star"],
    ["🌟", "star glow"],
    ["✨", "sparkles"],
    ["⚡", "zap lightning"],
    ["🔥", "fire"],
    ["💥", "boom"],
    ["💫", "dizzy star"],
    ["💦", "sweat drops"],
    ["💨", "dash"],
    ["❗", "exclaim"],
    ["❓", "question"],
    ["❕", "exclaim white"],
    ["❔", "question white"],
    ["‼️", "double exclaim"],
    ["⁉️", "exclaim question"],
    ["💯", "hundred"],
    ["🔆", "bright"],
    ["🔅", "dim"],
    ["🔱", "trident"],
    ["⚜️", "fleur de lis"],
    ["〽️", "part alt"],
    ["⚠️", "warning"],
    ["🚸", "children"],
    ["🔰", "beginner"],
    ["♻️", "recycle"],
    ["🈯", "reserved"],
    ["💹", "chart yen"],
    ["❇️", "sparkle"],
    ["✳️", "asterisk"],
    ["❎", "cross"],
    ["🌐", "globe"],
    ["💠", "diamond dot"],
    ["Ⓜ️", "metro"],
    ["🌀", "cyclone"],
    ["💤", "zzz sleep"],
    ["🏧", "atm"],
    ["🚾", "wc"],
    ["♿", "wheelchair"],
    ["🅿️", "parking"],
    ["🈳", "empty"],
    ["🈂️", "sa"],
    ["🛂", "passport"],
    ["🛃", "customs"],
    ["🛄", "baggage"],
    ["🛅", "left luggage"],
    ["🚹", "men"],
    ["🚺", "women"],
    ["🚼", "baby"],
    ["🚻", "restroom"],
    ["🚮", "litter"],
    ["🎦", "cinema"],
    ["📶", "signal"],
    ["🈁", "katakana"],
    ["🔣", "symbols"],
    ["ℹ️", "info"],
    ["🔤", "abc"],
    ["🔡", "abcd"],
    ["🔠", "ABCD"],
    ["🆖", "ng"],
    ["🆗", "ok"],
    ["🆙", "up"],
    ["🆒", "cool"],
    ["🆕", "new"],
    ["🆓", "free"],
    ["0️⃣", "0"],
    ["1️⃣", "1"],
    ["2️⃣", "2"],
    ["3️⃣", "3"],
    ["4️⃣", "4"],
    ["5️⃣", "5"],
    ["6️⃣", "6"],
    ["7️⃣", "7"],
    ["8️⃣", "8"],
    ["9️⃣", "9"],
    ["🔟", "10"],
    ["🔢", "numbers"],
    ["#️⃣", "hash"],
    ["*️⃣", "asterisk"],
    ["⏏️", "eject"],
    ["▶️", "play"],
    ["⏸️", "pause"],
    ["⏹️", "stop"],
    ["⏺️", "record"],
    ["⏭️", "next"],
    ["⏮️", "previous"],
    ["⏩", "fast forward"],
    ["⏪", "rewind"],
    ["⏫", "up"],
    ["⏬", "down"],
    ["◀️", "left"],
    ["🔼", "up"],
    ["🔽", "down"],
    ["➡️", "right"],
    ["⬅️", "left"],
    ["⬆️", "up"],
    ["⬇️", "down"],
    ["↗️", "up-right"],
    ["↘️", "down-right"],
    ["↙️", "down-left"],
    ["↖️", "up-left"],
    ["↕️", "up-down"],
    ["↔️", "left-right"],
    ["↩️", "right curve"],
    ["↪️", "left curve"],
    ["⤴️", "right up"],
    ["⤵️", "right down"],
    ["🔀", "shuffle"],
    ["🔁", "repeat"],
    ["🔂", "repeat one"],
    ["🔄", "refresh"],
    ["🔃", "clockwise"],
    ["🎵", "note"],
    ["🎶", "notes"],
    ["➕", "plus"],
    ["➖", "minus"],
    ["➗", "divide"],
    ["✖️", "multiply"],
    ["♾️", "infinity"],
    ["💲", "dollar"],
    ["💱", "currency"],
    ["™️", "tm"],
    ["©️", "copyright"],
    ["®️", "registered"],
    ["〰️", "wavy"],
    ["➰", "curly"],
    ["➿", "double curly"],
    ["🔚", "end"],
    ["🔙", "back"],
    ["🔛", "on"],
    ["🔝", "top"],
    ["🔜", "soon"],
    ["✔️", "check"],
    ["☑️", "checkbox"],
  ],
};

const RECENT_KEY = "pulsechat.recent.emojis";
const loadRecent = () => {
  try {
    return JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
  } catch {
    return [];
  }
};

export default function EmojiPicker({ onPick, onClose }) {
  const [tab, setTab] = useState("Smileys & People");
  const [q, setQ] = useState("");
  const [recent, setRecent] = useState(loadRecent);

  const categories = Object.keys(DATA);

  const list = useMemo(() => {
    if (q.trim()) {
      const needle = q.trim().toLowerCase();
      const out = [];
      Object.values(DATA).forEach((arr) => {
        arr.forEach(([e, k]) => {
          if (k.includes(needle) || e === needle) out.push(e);
        });
      });
      return [...new Set(out)];
    }
    if (tab === "Recent") return recent;
    return DATA[tab].map(([e]) => e);
  }, [q, tab, recent]);

  const pick = (emoji) => {
    const next = [emoji, ...recent.filter((x) => x !== emoji)].slice(0, 24);
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
    setRecent(next);
    onPick(emoji);
  };

  return (
    <div className="absolute bottom-full mb-2 left-2 right-2 sm:left-3 sm:right-auto sm:w-[380px] z-30 glass rounded-2xl shadow-2xl border border-white/10 overflow-hidden animate-pop-in">
      {/* search */}
      <div className="p-2.5 border-b border-white/5">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search emoji…"
            className="w-full pl-8 pr-3 py-2 rounded-lg bg-ink-900/60 border border-white/5 text-sm outline-none focus:border-brand-500/40"
          />
        </div>
      </div>

      {/* tabs */}
      <div className="flex items-center gap-1 px-2 py-1.5 border-b border-white/5 overflow-x-auto scroll-thin">
        <button
          onClick={() => {
            setTab("Recent");
            setQ("");
          }}
          className={`p-1.5 rounded-lg shrink-0 ${tab === "Recent" && !q ? "bg-brand-500/20 text-brand-400" : "text-slate-400 hover:bg-white/5"}`}
          title="Recent"
        >
          <Clock className="w-4 h-4" />
        </button>
        {categories.map((c) => (
          <button
            key={c}
            onClick={() => {
              setTab(c);
              setQ("");
            }}
            className={`px-2 py-1 rounded-lg text-[11px] font-medium whitespace-nowrap transition ${
              tab === c && !q
                ? "bg-brand-500/20 text-brand-400"
                : "text-slate-400 hover:bg-white/5"
            }`}
          >
            {c.split(" ")[0]}
          </button>
        ))}
      </div>

      {/* grid */}
      <div className="max-h-72 overflow-y-auto scroll-thin p-2">
        {list.length === 0 ? (
          <p className="text-center text-xs text-slate-500 py-8">
            {tab === "Recent" ? "No recent emojis" : "No emoji found"}
          </p>
        ) : (
          <div className="grid grid-cols-8 sm:grid-cols-9 gap-0.5">
            {list.map((e) => (
              <button
                key={e}
                onClick={() => pick(e)}
                className="text-xl p-1.5 rounded-lg hover:bg-white/10 transition"
              >
                {e}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
